name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: users_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build Application with Gradle
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BE_PROJECT_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BE_PROJECT_NAME }}:${{ github.sha }}

      - name: Tag and push latest
        if: github.ref_name == 'main'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BE_PROJECT_NAME }}:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BE_PROJECT_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BE_PROJECT_NAME }}:latest
  deploy-user-service:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Deploy User Service
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts for deployment
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy user-service using common docker-compose
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/${{ secrets.SERVER_USER }}/microservices
            echo "Pulling latest image for user-service..."
            docker-compose pull user-service
            echo "Deploying user-service..."
            docker-compose up -d user-service
            echo "Deployment of user-service completed at $(date)"
            docker-compose ps user-service
          EOF